import { ChunkType } from '@renderer/types/chunk'
import { describe, expect, it } from 'vitest'

import { AnswerCollector } from './AnswerCollector'
import {
  countCompleteIntegers,
  getModelTestMaxOutputTokens,
  MODEL_TEST_MAX_OUTPUT_BYTES,
  ModelTestOutputGuard
} from './OutputGuard'

describe('ModelTrace generation limits', () => {
  it('counts complete integers only, preserving signs, range errors and repetitions', () => {
    expect(countCompleteIntegers('1 1 -3 0 999 24', false)).toBe(5)
    expect(countCompleteIntegers('1 1 -3 0 999 247 ', false)).toBe(6)
    expect(countCompleteIntegers('1 1 -3 0 999 247', true)).toBe(6)
    expect(countCompleteIntegers('1.2 1e3 -1.2 <think>1 2 3</think> 5 ', false)).toBe(1)
  })
  it('permits 2N and interrupts the first complete excess number', () => {
    const guard = new ModelTestOutputGuard(317)
    const prefix = '1 '.repeat(634)
    expect(guard.accept({ type: ChunkType.TEXT_DELTA, text: prefix }, prefix)).toBeUndefined()
    expect(guard.accept({ type: ChunkType.TEXT_DELTA, text: '24' }, prefix + '24')).toBeUndefined()
    expect(guard.accept({ type: ChunkType.TEXT_DELTA, text: '7 ' }, prefix + '247 ')?.limit).toMatchObject({
      kind: 'integers',
      maximum: 634,
      actual: 635
    })
  })
  it('does not turn a normal terminal quantity mismatch into a transport failure', () => {
    const text = Array(635).fill('1').join(',')
    expect(new ModelTestOutputGuard(317).accept({ type: ChunkType.TEXT_COMPLETE, text }, text)).toBeUndefined()
  })
  it('records the first excess integer in one giant delta instead of the full chunk size', () => {
    const text = Array(1706).fill('1').join(' ')
    const limit = new ModelTestOutputGuard(317).accept({ type: ChunkType.TEXT_DELTA, text }, text)?.limit
    expect(limit).toMatchObject({ kind: 'integers', maximum: 634, actual: 635 })
    expect(limit?.position).toBeGreaterThan(0)
  })
  it('derives a bounded request budget from the challenge size', () => {
    expect(getModelTestMaxOutputTokens(10)).toBe(1024)
    expect(getModelTestMaxOutputTokens(303)).toBe(1212)
    expect(getModelTestMaxOutputTokens(2000)).toBe(4096)
  })
  it('counts native thinking and excluded commentary towards UTF-8 bytes', () => {
    const guard = new ModelTestOutputGuard(317)
    const hidden = '思'.repeat(10000)
    expect(guard.accept({ type: ChunkType.THINKING_DELTA, text: hidden }, '')).toBeUndefined()
    expect(guard.accept({ type: ChunkType.THINKING_COMPLETE, text: hidden }, '')).toBeUndefined()
    expect(
      guard.accept(
        { type: ChunkType.TEXT_DELTA, text: 'a'.repeat(3000), providerMetadata: { openai: { phase: 'commentary' } } },
        ''
      )?.limit
    ).toEqual({ kind: 'bytes', maximum: MODEL_TEST_MAX_OUTPUT_BYTES, actual: 33000 })
  })
  it('does not count block or final snapshots as extra generated bytes', () => {
    const collector = new AnswerCollector()
    const guard = new ModelTestOutputGuard(317)
    const text = '<think>' + 'x'.repeat(18000) + '</think>' + '1 '.repeat(317)
    for (const chunk of [
      { type: ChunkType.TEXT_START },
      { type: ChunkType.TEXT_DELTA, text: text.slice(0, 100) },
      { type: ChunkType.TEXT_DELTA, text: text.slice(100) },
      { type: ChunkType.TEXT_COMPLETE, text },
      { type: ChunkType.TEXT_COMPLETE, text },
      { type: ChunkType.LLM_RESPONSE_COMPLETE, response: { text } }
    ] as any[]) {
      collector.accept(chunk)
      expect(guard.accept(chunk, collector.rawText)).toBeUndefined()
    }
    expect(collector.rawText).toBe(text)
    expect(countCompleteIntegers(collector.rawText, true)).toBe(317)
  })
})
